### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe Kafka byte",
  "email": "john.doe.kafka.byte@example.com",
  "address": "123 kafka-ser street",
  "dateOfBirth": "1999-09-09",
  "registeredDate": "2021-12-09"
}
###